#+LATEX_CLASS_OPTIONS: [12pt]
#+OPTIONS: num:nil toc:nil
#+LATEX_HEADER: \usepackage[sc, osf]{mathpazo}
#+LATEX_HEADER: \usepackage[euler-digits, small]{eulervm}
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \usepackage{mathrsfs}
#+LATEX_HEADER: \usepackage{titlesec}
#+LATEX_HEADER: \usepackage[left = 2cm, right = 2cm, top = 2cm, bottom = 2cm]{geometry}
#+LATEX_HEADER: \def\R{\mathbb{R}}
#+LATEX_HEADER: \def\x{\mathbf{x}}
#+LATEX_HEADER: \def\mob{\textup{M{\"o}bius}}
#+LATEX_HEADER: \def\C{\mathbb{C}}
#+LATEX_HEADER: \def\P{\mathbb{P}}
#+LATEX_HEADER: \def\Cinf{C^{\infty}}
#+LATEX_HEADER: \def\A{\mathscr{A}}
#+LATEX_HEADER: \def\E{\mathscr{E}}
#+LATEX_HEADER: \renewcommand{\theenumi}{(\alph{enumi})}
#+LATEX_HEADER: \newcommand\sectionbreak{\clearpage}

* Chapter 1
** 2
*** 2.1
    I think that by "arc", the author is referring to path. (Spivak
    uses arc to refer to one-one path.) In that case, this is easy.
** 3
*** 3.1
    The center of a group $G$ is the set of all elements $z$ such that
    $z \cdot g = g \cdot z$.

    If two path classes gives rises to the same isomorphism if and
    only if $\gamma' \gamma^{-1}$ belongs to the center of the group
    $\pi (X, x)$.
*** 3.2
    We claim the following: this is equivalent to:

    Fix a point $x$; if for all values of $y$, and all path class
    $\gamma$ and $\gamma'$ connecting $x$ and $y$, $\gamma'
    \gamma^{-1}$ be an element of the center of the group.

    Basically this is an extension of the result from problem 3.1. The
    only difference is that we can simply state the equivalence for a
    fixed $x$ and this would be equivalent for any point in $X$ too.
*** 3.3
    Suppose $f \sim g$, then $f \cdot \bar{g} = g \cdot \bar {g} =
    \E_x \in \pi (X, x)$.

    Suppose $f \cdot \bar{g} = \E_x$, then $f \cdot \bar{g} g = \E_x
    \cdot g \implies f \cdot \E_y = g \implies f = g$.
** 4
   
