#+latex_class_options: [12pt]
#+options: num:nil toc:nil
#+latex_header: \usepackage{lmodern}
#+latex_header: \usepackage[T1]{fontenc}
#+latex_header: \usepackage{sectsty}
#+latex_header: \usepackage{amscd}
#+latex_header: \usepackage{parskip}
#+latex_header: \usepackage{mathrsfs}
#+latex_header: \usepackage{titlesec}
#+latex_header: \usepackage[left = 2cm, right = 2cm, top = 2cm, bottom = 2cm]{geometry}
#+latex_header: \sectionfont{\centering}
#+latex_header: \subsectionfont{\centering}
#+latex_header: \def\R{\mathbb{R}}
#+latex_header: \def\Z{\mathbb{Z}}
#+latex_header: \def\Q{\mathbb{Q}}
#+latex_header: \def\x{\mathbf{x}}
#+latex_header: \def\mob{\textup{M{\"o}bius}}
#+latex_header: \def\C{\mathbb{C}}
#+latex_header: \def\P{\mathbb{P}}
#+latex_header: \def\Cinf{C^{\infty}}
#+latex_header: \def\A{\mathscr{A}}
#+latex_header: \def\E{\mathscr{E}}
#+latex_header: \def\tX{\tilde{X}}
#+latex_header: \def\bs{\textforwardslash}
#+latex_header: \def\Im{\operatorname{Im}}
#+latex_header: \def\P{\mathbb{P}}
#+latex_header: \renewcommand{\theenumi}{(\alph{enumi})}
#+latex_header: \newcommand\sectionbreak{\clearpage}

* Chapter 2
  
** 2
*** 2.1
    I think that by "arc", the author is referring to path. (Spivak
    uses arc to refer to one-one path.) In that case, this is easy.
** 3
*** 3.1
    The center of a group $G$ is the set of all elements $z$ such2 that
    $z \cdot g = g \cdot z$.

    If two path classes gives rises to the same isomorphism if and
    only if $\gamma' \gamma^{-1}$ belongs to the center of the group
    $\pi (X, x)$.
*** 3.2
    We claim the following: this is equivalent to:

    Fix a point $x$; if for all values of $y$, and all path class
    $\gamma$ and $\gamma'$ connecting $x$ and $y$, $\gamma'
    \gamma^{-1}$ be an element of the center of the group.

    Basically this is an extension of the result from problem 3.1. The
    only difference is that we can simply state the equivalence for a
    fixed $x$ and this would be equivalent for any point in $X$ too.
*** 3.3
    Suppose $f \sim g$, then $f \cdot \bar{g} = g \cdot \bar {g} =
    \E_x \in \pi (X, x)$.

    Suppose $f \cdot \bar{g} = \E_x$, then $f \cdot \bar{g} g = \E_x
    \cdot g \implies f \cdot \E_y = g \implies f \sim g$.
** 4
*** TODO 4.1
*** 4.2
    Recall that $X$ is Hausdorff if and only if the diagonal $\Delta =
    \{x\times x \vert x \in X\}$ is closed.
    
    Given two maps $f, g \colon X \rightarrow Y$, then the set $A =
    \{x \in X \vert f(x) = g(x)\}$ is closed if $Y$ is Hausdorff. This
    can be proved by making use of the above observation, since $A =
    (f \times g)^{-1} (\Delta)$.

    Let $f\colon X \rightarrow X$ be a retraction mapping from $X$
    onto $Z$ and $i\colon X \rightarrow X$ be the identity map. Then
    the points where both these map are equal is clearly the set $Z$
    which will become closed.
*** 4.3

    We need to show that $\pi(X) = \Im {i_{*}} \times \ker
    {r_{*}}$. Since $\Im{i_{*}} \approx \pi(A)/\ker{i_{*}}$ and
    $\ker{r_{*}} \approx \pi(X) / \Im{r_{*}}$, it is enough to show that
    $\pi(X) \approx \pi(A) \times \pi(X/A)$.

    The last result follows from the fact that $\pi (A)$ is a normal
    subgroup of $\pi(X)$ and observing that the map $(n, g) \mapsto
    ng$ is an isomorphism between $N \times (G / N)$ and $G$ (here $G$
    is an arbitrary group and $N$ is a normal subgroup of $G$.)
    
*** 4.4
    Suppose $A$ be a retract of $X$ and $r \colon X \rightarrow A$ be
    the corresponding retraction. Then define a function $\phi \colon
    X \times Y \rightarrow A \times Y$ by $\phi (x, y) = (r (x),
    y)$. This function is clearly continuous and thus forms a
    retraction mapping from $X \times Y$ onto $A \times Y$.

    Suppose that there is a retraction $\phi \colon X \times Y
    \rightarrow A \times Y$. Define a retraction $r \colon X \times A$
    by first picking a point $y_0 \in Y$ and by making $r(x) = \pi_1
    \circ \phi (x, y_0)$. Once again one can verify that this mapping
    is a retraction.
*** 4.5
    This is easy. Compose the two retraction mappings to get the
    required retraction.
*** 4.6
    Without loss of generality, one can assume that the $(n-1)$
    dimensional sphere $S^{n-1}$ is the unit-sphere centered at the
    origin and the point $x_0$ is the origin.

    Let $X = \R^n - \{0\}$, then define the function $\phi \colon X
    \times I \rightarrow X$ by

    $$\phi (x, t) = (1 - t) x + t\cdot\frac{x}{\Vert x \Vert}.$$

    One can verify that this is indeed the required deformation
    retract.
*** 4.7
    The center circle.
*** TODO 4.8
*** TODO 4.9
*** 4.10
    Suppose that $f_0$ and $f_1$ be any two path connecting $x$ and
    $y$. Consider the path from $x$ to $x$ given by $\gamma = f_0
    \cdot f_1^{-1}$.

    Since the space is a deformation retract to a single point, the
    fundamental group $\pi (X, x)$ is isomorphic to the trivial group
    $\{e\}$, i.e., $\gamma$ is identity. This shows that $f_0$ and
    $f_1$ are equivalent.
*** TODO 4.11
** 5
*** 5.1
    Given a loop $f \colon I \rightarrow X$ based on $x_0$, we need to
    prove that this belongs to the trivial class.

    Suppose $f (I)$ is entirely contained in one of $U_i$, since $U_i$
    is simply connected, the fact that $f$ belongs to trivial class is
    obvious. We assume that $f(I)$ is contained is not completed
    contained in a single $U_i$.

    Define a class of open sets $V_i = f^{-1}(U_i)$. Since $[0, 1]$ is
    compact and since $V_i$ is an open cover of $[0, 1]$, there exists
    a real number, $\varepsilon$ (the Lebesgue number corresponding to
    the open cover), such that any set whose diameter is less than
    $\varepsilon$ is completely contained in one of $U_i$.

    Thus we can find a sequence $0 = t_1 < t_2 < \cdots < t_n = 1$
    such that the following conditions are satisfied for all $i$:

    1. $f([t_i, t_{i+1}]) \subset U_j$ for all some $j$;
       
    2. $f([t_i, t_{i+1}])$ and $f([t_{i+1}, t_{i+2}])$ are not
       entirely contained in same $U_j$ for some $j$.

    This can be constructed in the following fashion: pick $t_i$ such
    that the condition on diameter is satisfied. This guarantees the
    first condition. If for consecutive intervals lies completely
    inside a single $U_i$, simply merge the intervals to produce a
    larger one; repeat this procedure until the second condition is
    satisfied.

    This basically implies that for every value of $i$, $f(t_i)$
    belongs to the intersection of $U_j$ and $U_k$ for some value of
    $j$ and $k$.

    Let us denote the path component corresponding to $f$ as $\beta$
    and the ones that correspond to the restriction of $f$ on the
    sub intervals as $\beta_i$. It is easy to see that

    $$\beta = \beta_1\cdot \beta_2 \cdot \cdots.$$

    Since $f(t_i)$ will always belong to the intersection, we can
    think of a path $\gamma_i$ that connects $f(t_i)$ and the point
    $x_0$. Define the loop classes $\delta_i$ in the following manner:

    $$\delta_1 = \beta_1 \gamma_1,$$
    
    $$\delta_i = \gamma_{i - 1}^{-1}\beta_i \gamma^{i} \textup{ for }
    1 < i < n,$$
    
    $$\delta_n = \gamma_{n-1}^{-1} \beta_n.$$ (if $n$ is finite.)

    It is easy to see that

    $$\beta = \delta_1\cdot \delta_2 \cdots.$$

    Observe that each $\delta_i$ is a loop at $x_0$ and lying entirely
    inside $U_i$, i.e., trivial. We have shown that $f$ can be
    decomposed as loops of trivial classes, i.e., $f$ belongs to the
    trivial loop class. $\blacksquare$

    *Special cases*

    1. Let $X$ be a topological space and $U_1$, $U_2$ be two open
       sets that cover $X$ that has at least one point in
       common. Suppose these open sets are simply connected and if
       $U_1 \cap U_2$ is an arc wise connected space, then $X$ is
       simply connected.
       
    2. Let $\{U_i\}$ be a nonempty open cover of $X$ such that $U_i
       \subset U_j$ whenever $i < j$. Suppose each of $U_i$ are arc
       connected and simply connected. Then the space $X$ is simply
       connected.
       
*** 5.2
    We make use of the Stereographic projection of $S^n$. Let $p$ and
    $-p$ represent two antipodal points of $S^n$, then there exists
    two homeomorphisms $f\colon S^n - \{p\} \rightarrow \R^n$ $g\colon
    S^n - \{-p\} \rightarrow \R^n$. This shows that the open subsets
    $S^n - \{p\}$ and $S^n - \{-p\}$, which has a arc connected
    intersection whenever $n \ge 2$ (this is not true for $n = 1$),
    are also simply connected. From previous exercise, we see that
    $S^n$ is simply connected.
    
*** 5.3
    $R^2 - \{0\}$ is not simply connected while $R^n - \{0\}$ is
    simply connected for $n > 2$.

*** 5.4
    A homeomorphism cannot map a point of $S^1$ to a point in the
    interior of $E^2$. This is because, there is no neighborhood of a
    point on the boundary that is homeomorphic $\R^2$ while there are
    neighborhoods of $E^2$ that are homeomorphic to $\R^2$.
    
    Alternatively, one can see that deleted neighborhoods of a point
    on the boundary are simply connected while this is not the case
    with a point on the interior of $D^2$.

** 7
*** 7.1
    A torus is $S^1 \times S^1$, thus $\pi (S^1 \times S^1) = \Z
    \times \Z$.
*** 7.2
    Consider the retract $r\colon S^1 \times S^1 \rightarrow S^1
    \times \{p\}$ defined by $r(x, y) = (x, p)$. This is clearly, a
    continuous map. 
    
    Recall that, if $A$ is a deformation retract of $X$, then the
    inclusion map induces an isomorphism of $\pi (A, a)$ onto $\pi (X,
    a)$ for any $a \in A$. Observe that the group $\Z \times \Z$ is
    not isomorphic to $\Z$ (the first one is cyclic.)
* Chapter 3

** 3

*** 3.1

    Let $F'$ denote the subgroup of $F$ that is generated by elements
    of $\varphi (S)$. Given an Abelian group $A$, there is a
    homomorphism $g$ that makes the diagram in the textbook
    commutative (lazy to draw it here.)

    Firstly we shall show that $F'$ shall also satisfy the hypothesis
    required for free group over $S$. This can be seen from the fact
    that the mep $g\vert_{F'}$ is a homomorphism between $F'$ and $A$
    which also makes the diagram (in the book) commutative. From
    Proposition 3.1, $F'$ and $F$ are isomorphic.

    Since $F$ is Abelian, here is a unique homomorphism between $F'$
    and $F$ that makes the diagram commutative. Clearly identity is the
    unique homomorphism, thus $F' = F$.
    
*** 3.2
    
    We proceed similarly Corollary 3.5. If $F$ and $F'$ are
    isomorphic, then $F/F^n$ and $F'/(F')^n$ should also be
    isomorphic. But the former is finite, while the latter is infinite
    (the latter can be thought of as the weak product of infinitely
    many $\Z_n$, which is clearly an infinite group.)

*** 3.3

   Reference: [[http://www.math.uni-duesseldorf.de/~schroeer/publications_pdf/infinite_product-1.pdf][Baer's Result: The infinite product of integers has no
   basis]].

   An example is the group $\Q$ under addition. This is clearly an
   Abelian group. Assume that this is free and let $S$ be a basis for
   $\Q$.

   Let $1/1$ be represented as $1/1 = n_1 s_{\alpha_1} + \cdots + n_k
   s_{\alpha_k}$ where $n_1, \cdots, n_k$ are integers and WLOG $n_1
   \neq 0$.

   Let $n$ be an integer that does not divide $n_1$. The number $1/n$
   has the representation $1/n = m_1s_{\beta_1} + \cdots + m_j
   s_{\beta_j}$. This implies that $nm_1s_{\beta_1} + \cdots + nm_j
   s_{\beta_j} = n_1 s_{\alpha_1} + \cdots + n_ks_{\alpha_{k}}$, which
   is a contradiction.

   The reference paper proves that the direct product of countable
   number of $\Z$ does not have a basis, and hence cannot be a free
   Abelian group. 

*** 3.4

    The split is $\Z_{36} \times \Z_{2}$. 
    
*** TODO 3.5

** 4
   
*** 4.1

    Suppose $x_1$ and $x_2$ are elements belonging to two different
    groups. Then $x_1x_2$ and $x_2x_1$ are elements that are not
    equal, since $x_1x_2x_1x_2 \neq 1$; thus the free product results
    in a non Abelian group.

    Notice that $x_1x_2x_1x_2\cdots x_1x_2$ ($n$ times) is a reduced
    word. If this is equal to the identity element, then from
    uniqueness of the representation of elements of the direct
    product, one can see that all of them has to be equal to identity,
    which is a contradiction. This proves that the element $x_1x_2$ is
    of infinite order.

    To show that the center contains only identity, given an arbitrary
    element $y$, let $y_1 \in G_{y_1}$ denote the first element of the
    word $y$ and $y_2$ denote an element other than unity in and not
    contained in $G_{y_1}$. Clearly $yy_2 \neq y_2y$ (using the
    uniqueness of the reduced word representation.)
    
*** 4.2

    Let $G$ denote the free product of $\{G_i\}$ and $G'$ denote the
    free product of $\{G'_i\}$. Let $\varphi_i$ denote the inclusion
    homomorphism between $G_i$ and $G$ and $\varphi_i'$ denote the
    inclusion homomorphism between $G_i'$ and $G'$.

    Since $\varphi_i$ is also a homomorphism between $G'_i$ and $G$,
    there exists a unique homomorphism $k\colon G' \rightarrow G$ such
    that $k \circ \varphi'_i = \varphi_i$. It is enough to show that
    the kernel of $k$ is trivial. This follows from the fact that
    $\varphi_i$ is a monomorphism for all values of $i$. 

*** 4.3

    Since $\varphi'_i \circ f_i \colon G_i \rightarrow G'$ is a
    homomorphism, we observe that there is a unique homomorphism
    $f\colon G \rightarrow G'$ such that $f \circ \varphi_i =
    \varphi'_i \circ f_i$. This fact makes the diagram (given in the
    problem) commutative.

    Suppose each $f_i$ be a monomorphism, then $f$ is also a
    monomorphism. Similarly, one can show that $f$ is an epimorphism
    if each $f_i$ is an epimorphism (making use of the fact that every
    element of the free product is equal to a finite product of
    elements of the corresponding family.)

*** 4.4

** 5
   
*** 5.1

    This follows from Exercise 4.1 (basically says that the free
    product of a collection of groups, each containing more than one
    element is not Abelian.)
    
*** 5.2

    Again, this follows from Exercise 4.1

*** TODO 5.3

*** 5.4

    If $S$ if finite and $S'$ be an infinite set, if $F$ and $F'$ are
    isomorphic, then so are $F/[F, F]$ and $F'/[F', F']$. But $F/[F,
    F]$ and $F'/[F', F']$ are free Abelian groups with "generating
    sets" of different cardinality and hence non-isomorphic.

*** 5.5

* Chapter 4

** 3
   
*** 3.1

    First observe that no two $V_i$ and $V_j$ is a proper subset of
    the other. Thus the only possibility of $\varphi_{\lambda \mu}$ is
    the inclusion homomorphism between $W$ and $V_i$. Let us denote
    this by $\varphi_i \colon \pi (W) \rightarrow \pi (V_i)$.

    The exercise immediately follows from theorem 2.2.
    
*** 3.2
    For every $i \in I$, let $a_i$ be a point in $A_i$ that is not
    equal to $x_0$. Let $B_i$ denote the set $A_i - \{a_i\}$; this set
    is open relative to $A_i$. Let us denote $A_i \cap_{j \neq i} B_i$
    by $C_i$; $C_i$ is open in $X$ and such that it is deformation
    retract to $A_i$. Let $W$ be the set $\cap B_i$; $W$ is open in $X$.

    Observe that $X = W \cap_{i}A_i$. This exercise now follows from
    exercise 3.1.

    (Refer to Example 1.21 in Hatcher.)

*** 3.3
    Shrinking wedge of circles is an example!

    Refer to example 1.25 in Hatcher.

*** 3.4
    The space $Y$ can be deformed into a countable wedge sum of
    circles. The fundamental group of this space is the free group on
    a countable space.

*** 3.5
    If we remove an 8-curve from a torus, we get an open set in Torus,
    which can be deformed to a point. From exercise 3.1, it is easy to
    see that the fundamental group of $X$ the Free product of $\Z
    \times \Z$ and $\Z \times \Z$.

** 4
   
*** TODO 4.1
    1. Since $\varphi_2$ is an isomorphism and onto; we have a
       homomorphism $\varphi \colon \pi(V) \rightarrow \pi(U) =
       \varphi_1 \circ \varphi_2^{-1}$. Apply the hypothesis of
       Theorem 2.1 to $H = \pi(U)$ and maps $\textup{id}, \varphi,
       \varphi_1$, we see that there is a unique homomorphism
       $\sigma\colon \pi(X) \rightarrow \pi(U)$ such that $\sigma
       \circ \psi_1 = \textup{id}$. The one-one-ness of $\psi_1$ is
       immediate.

       Recall that $\pi (X)$ is generated by $\psi_1(\pi(U))$ and
       $\psi_2(\pi(V)) = \psi_1 \circ \varphi_1 \circ \varphi_2^{-1}
       (\pi(V))$. Thus $\varphi_1$ has to be an onto mapping and hence
       an onto isomorphism!

    2.

* Chapter 5

** 2

*** TODO 2.1
(a) $\implies$ (d)

For every point $x$ and every neighborhood $U$ of $x$, from (a), the
arc components of $U$ are open. Let $V$ be the arc component of $U$
that contains $x$. It is seen that this neighborhood $V$ satisfies the
required conditions for (d).

*** 2.2
I think that one can demonstrate that if $f$ is a local Homeomorphism,
then, for every subset $A$ of $X$, $f\vert_A$ is also a local
Homeomorphism.

*** 2.3
Suppose $A = f^{-1}(\{y\})$ be an infinite set. Corresponding to each
point $x \in A$, there is an open set $U_x$ such that $f$ restricted
over $U_x$ is a homeomorphism. Notice that $U_x$ cannot have points in
$A$ other than $x$. For points $x'$ of $X$ that are not in $A$,
consider $U_{x'}$ to be its neighborhood such that $f$ can be
restricted to a homeomorphism. Again this neighborhood cannot contain
more than two points of $A$. Now $\{U_{x}\} \cap \{U_{x'}\}$ forms a
covering of $X$. If it has finite sub-cover, we have an obvious
contradiction.

Suppose $Y$ is a connected Hausdorff space, let $A$ denote the set of
all $y$ such that $f^{-1}(\{y\})$ is non-empty. Since $A$ is
non-empty, to prove the $A = Y$, it is enough to show that $A$ is both
open and closed.

Observe that $f$ is an open mapping, open-ness of $A$ follows from
this. Note that $A = f(X)$, since $X$ is compact $A$ is also compact
subset of $Y$, the closed-ness of $A$ follows from the fact that the
space $Y$ is Hausdorff.

*** TODO 2.4

** 6

*** 6.1
Consider the universal cover $(X, \text{id})$ of $X$ and the cover
$(\tilde{X}, p)$, let $\varphi$ be the homomorphism between $X$ and
$\tX$, i.e., $p \circ \varphi = \text{id}$. The onto-ness of $p$ is
immediate.

*** 6.2
1. $S^1$ has the fundamental group $\Z$, the subgroups of $\Z$ are of
   the form $n\Z$, and since the group is Abelian, the conjugacy class
   of a subgroup is the singleton set the subgroup.

   For $n = 0$, consider the covering space $(\R, t \mapsto (\cos t,
   \sin t))$. For other values of $n$, consider the cover $(S^1,
   \theta \mapsto n\theta)$. It is easily seen that these covering
   spaces determines all the covering spaces of $S^1$ upto
   isomorphism.

2. The fundamental group of the projective plane is $\Z_{2} = \{0,
   1\}$. There are only trivial subgroups. $(S^2, p \mapsto [p])$, and
   $(\P^2, [p] \mapsto [p])$ determines all covering spaces upto
   isomorphism.

3.

*** 6.5

** 7

*** 7.2
1. Example 2.2. The covering space $S^1$ where $S^1$ wraps around
   $S^1$, $n$ times. The group of Automorphisms will be $\Z_n$.

2. Example 2.4.

** 8

*** 8.1
Let $G=\{\varphi_1, \cdots, \varphi_n\}.$ Let $y\in Y$, define $y_i =
\varphi_i(y)$. For each $y_i$, let $V_i$ be a neighborhood of $y_i$
that is disjoint from all other $y_j$. Define $U_i =
\varphi_{i}(V_i)$, then $\cap U_i$ is a neighborhood of $y$ such that
$\varphi_i(U)$ is disjoint (pair-wise.)

*** 8.2
