#+LATEX_CLASS_OPTIONS: [12pt]
#+OPTIONS: num:nil toc:nil
#+LATEX_HEADER: \usepackage[sc, osf]{mathpazo}
#+LATEX_HEADER: \usepackage[euler-digits, small]{eulervm}
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \usepackage{mathrsfs}
#+LATEX_HEADER: \usepackage{titlesec}
#+LATEX_HEADER: \usepackage[left = 2cm, right = 2cm, top = 2cm, bottom = 2cm]{geometry}
#+LATEX_HEADER: \def\R{\mathbb{R}}
#+LATEX_HEADER: \def\x{\mathbf{x}}
#+LATEX_HEADER: \def\mob{\textup{M{\"o}bius}}
#+LATEX_HEADER: \def\C{\mathbb{C}}
#+LATEX_HEADER: \def\P{\mathbb{P}}
#+LATEX_HEADER: \def\Cinf{C^{\infty}}
#+LATEX_HEADER: \def\A{\mathscr{A}}
#+LATEX_HEADER: \def\E{\mathscr{E}}
#+LATEX_HEADER: \renewcommand{\theenumi}{(\alph{enumi})}
#+LATEX_HEADER: \newcommand\sectionbreak{\clearpage}

* Chapter 1
** 2
*** 2.1
    I think that by "arc", the author is referring to path. (Spivak
    uses arc to refer to one-one path.) In that case, this is easy.
** 3
*** 3.1
    The center of a group $G$ is the set of all elements $z$ such that
    $z \cdot g = g \cdot z$.

    If two path classes gives rises to the same isomorphism if and
    only if $\gamma' \gamma^{-1}$ belongs to the center of the group
    $\pi (X, x)$.
*** 3.2
    We claim the following: this is equivalent to:

    Fix a point $x$; if for all values of $y$, and all path class
    $\gamma$ and $\gamma'$ connecting $x$ and $y$, $\gamma'
    \gamma^{-1}$ be an element of the center of the group.

    Basically this is an extension of the result from problem 3.1. The
    only difference is that we can simply state the equivalence for a
    fixed $x$ and this would be equivalent for any point in $X$ too.
*** 3.3
    Suppose $f \sim g$, then $f \cdot \bar{g} = g \cdot \bar {g} =
    \E_x \in \pi (X, x)$.

    Suppose $f \cdot \bar{g} = \E_x$, then $f \cdot \bar{g} g = \E_x
    \cdot g \implies f \cdot \E_y = g \implies f \sim g$.
** 4
*** TODO 4.1
*** 4.2
    Recall that $X$ is Hausdorff if and only if the diagonal $\Delta =
    \{x\times x \vert x \in X\}$ is closed.
    
    Given two maps $f, g \colon X \rightarrow Y$, then the set $A =
    \{x \in X \vert f(x) = g(x)\}$ is closed if $Y$ is Hausdorff. This
    can be proved by making use of the above observation, since $A =
    (f \times g)^{-1} (\Delta)$.

    Let $f\colon X \rightarrow X$ be a retraction mapping from $X$
    onto $Z$ and $i\colon X \rightarrow X$ be the identity map. Then
    the points where both these map are equal is clearly the set $Z$
    which will become closed.
*** TODO 4.3
    
*** 4.4
    Suppose $A$ be a retract of $X$ and $r \colon X \rightarrow A$ be
    the corresponding retraction. Then define a function $\phi \colon
    X \times Y \rightarrow A \times Y$ by $\phi (x, y) = (r (x),
    y)$. This function is clearly continuous and thus forms a
    retraction mapping from $X \times Y$ onto $A \times Y$.

    Suppose that there is a retraction $\phi \colon X \times Y
    \rightarrow A \times Y$. Define a retraction $r \colon X \times A$
    by first picking a point $y_0 \in Y$ and by making $r(x) = \pi_1
    \circ \phi (x, y_0)$. Once again one can verify that this mapping
    is a retraction.
*** 4.5
    This is easy. Compose the two retraction mappings to get the
    required retraction.
*** 4.6
    Without loss of generality, one can assume that the $(n-1)$
    dimensional sphere $S^{n-1} is the unit-sphere centered at the
    origin and the point $x_0$ is the origin.

    Let $X = \R^n - \{0\}$, then define the function $\phi \colon X
    \times I \rightarrow X$ by

    $$\phi (x, t) = (1 - t) x + t\cdot\frac{x}{\Vert x \Vert}.$$

    One can verify that this is indeed the required deformation
    retract.
*** 4.7
    The center circle.
*** TODO 4.8
*** TODO 4.9
*** 4.10
    Suppose that $f_0$ and $f_1$ be any two path connecting $x$ and
    $y$. Consider the path from $x$ to $x$ given by $\gamma = f_0
    \cdot f_1^{-1}.$

    Since the space is a deformation retract to a single point, the
    fundamental group $\pi (X, x)$ is isomorphic to the trivial group
    $\{e\}$, i.e., $\gamma$ is identity. This shows that $f_0$ and
    $f_1$ are equivalent.
*** TODO 4.11
